#!/usr/bin/env cwl-runner

cwlVersion: "cwl:draft-3"

class: CommandLineTool
baseCommand: ['cnvkit.py', 'import-picard']

requirements:
  - class: InlineJavascriptRequirement

description: |
  Convert Picard CalculateHsMetrics tabular output to CNVkit .cnn files.
  
      The input file is generated by the PER_TARGET_COVERAGE option in the
      CalculateHsMetrics script in Picard tools.
      

inputs:


- id: targets
  type:
  - "null"
  - type: array
    items: string

  default: ['.']
  description: Sample coverage .csv files (target and antitarget), or the
                directory that contains them.
  inputBinding:
    position: 1


- id: output_dir
  type: ["null", string]
  default: .
  description: Output directory name.
  inputBinding:
    position: 2
    prefix: --output-dir 
outputs:
    []
